import type { Tournament, Course, GolferProfile, NewAccount } from './types'
import { withCourseDefaults, withTournamentDefaults } from './golf'

export const MOCK_PROFILE: GolferProfile = {
  firstName: 'Alexander',
  lastName: 'Hartwell',
  email: 'alex.hartwell@golfclub.com',
  phone: '+1 (404) 555-0192',
  country: 'United States',
  city: 'Augusta, Georgia',
  dob: '1988-03-14',
  gender: 'Male',
  handicapIndex: 6.4,
  memberSince: 'January 2019',
  tournamentsPlayed: 23,
  wins: 4,
  avatarInitials: 'AH',
  emergencyContactName: 'Claire Hartwell',
  emergencyContactPhone: '+1 (404) 555-0147',
  handicapBody: 'USGA (GHIN)',
  handicapNumber: '10483327',
  homeClub: 'Augusta Pines Golf Club',
  preferredTee: 'Blue',
  dietary: ['None'],
  shirtSize: 'L',
  membership: 'Member',
  hasHandicap: true,
  preferredContact: 'Email',
  emailVerified: true,
}

/** Replaces the mock profile with a newly created account (prototype only — no backend) */
export function applyNewAccount(a: NewAccount) {
  const [first, ...rest] = a.fullName.trim().split(/\s+/)
  const firstName = a.firstName ?? first
  const lastName = a.lastName ?? rest.join(' ')
  Object.assign(MOCK_PROFILE, {
    firstName,
    lastName,
    email: a.email.trim(),
    phone: a.phone.trim(),
    dob: a.dob,
    gender: a.gender,
    ratingsGender: a.ratingsGender,
    street: a.street ?? '',
    city: a.city ?? '',
    region: a.region ?? '',
    postalCode: a.postalCode ?? '',
    country: a.country,
    handicapIndex: parseFloat(a.handicapIndex) || 0,
    hasHandicap: a.hasHandicap,
    handicapUpdated: a.hasHandicap ? new Date().toISOString().slice(0, 10) : undefined,
    memberSince: new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }),
    tournamentsPlayed: 0,
    wins: 0,
    avatarInitials: ((firstName?.[0] ?? '') + (lastName?.[0] ?? '')).toUpperCase() || '?',
    emergencyContactName: a.emergencyContactName.trim(),
    emergencyContactPhone: a.emergencyContactPhone.trim(),
    emergencyContactRelationship: a.emergencyContactRelationship,
    handicapBody: a.handicapBody,
    handicapNumber: a.handicapNumber.trim(),
    homeClub: a.homeClub.trim(),
    preferredTee: a.preferredTee,
    dietary: a.dietary,
    dietaryNote: a.dietaryNote,
    shirtSize: '',
    membership: a.membership,
    preferredContact: a.preferredContact,
    marketingOptIn: a.marketingOptIn,
    emailVerified: a.emailVerified,
  } satisfies Partial<GolferProfile>)
}

export const MOCK_COURSES: Course[] = [
  {
    id: 'c1',
    geo: { lat: 33.5021, lng: -82.0226 },
    phone: '+1 (706) 555-0100',
    website: 'augustapines.com',
    dressCode: 'Collared shirts; no denim. Soft spikes only.',
    name: 'Augusta Pines Golf Club',
    imageUrl: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&h=500&fit=crop&auto=format',
    location: 'Augusta, Georgia, USA',
    address: '2604 Washington Road',
    city: 'Augusta',
    region: 'Georgia',
    country: 'United States',
    description:
      'Augusta Pines Golf Club is a championship-calibre course carved through ancient longleaf pine forest. Designed by Robert Trent Jones Jr. in 1978, its undulating fairways and fast bentgrass greens demand precision at every level. The signature 16th hole — a 230-yard carry over a shimmering lake — is widely considered one of the finest par-3s in the American South.',
    holes: 18,
    par: 72,
    yardage: 7_420,
    rating: 75.8,
    slope: 141,
    established: '1978',
    designer: 'Robert Trent Jones Jr.',
    tournamentId: 't1',
    holeData: [
      { hole: 1,  par: 4, yards: 445, handicap: 7  },
      { hole: 2,  par: 5, yards: 575, handicap: 13 },
      { hole: 3,  par: 3, yards: 190, handicap: 17 },
      { hole: 4,  par: 4, yards: 465, handicap: 3  },
      { hole: 5,  par: 4, yards: 410, handicap: 11 },
      { hole: 6,  par: 5, yards: 540, handicap: 1  },
      { hole: 7,  par: 3, yards: 175, handicap: 15 },
      { hole: 8,  par: 4, yards: 430, handicap: 5  },
      { hole: 9,  par: 4, yards: 480, handicap: 9  },
      { hole: 10, par: 4, yards: 425, handicap: 8  },
      { hole: 11, par: 5, yards: 560, handicap: 12 },
      { hole: 12, par: 3, yards: 210, handicap: 16 },
      { hole: 13, par: 4, yards: 460, handicap: 4  },
      { hole: 14, par: 4, yards: 390, handicap: 10 },
      { hole: 15, par: 5, yards: 595, handicap: 2  },
      { hole: 16, par: 3, yards: 230, handicap: 18 },
      { hole: 17, par: 4, yards: 455, handicap: 6  },
      { hole: 18, par: 4, yards: 485, handicap: 14 },
    ],
  },
  {
    id: 'c2',
    geo: { lat: 36.5674, lng: -121.9480 },
    phone: '+1 (831) 555-0170',
    website: 'coastallinks.com',
    dressCode: 'Collared shirts; no denim. Soft spikes only.',
    name: 'Coastal Links at Carmel Bay',
    imageUrl: 'https://images.unsplash.com/photo-1592919505780-303950717480?w=800&h=500&fit=crop&auto=format',
    location: 'Carmel-by-the-Sea, California, USA',
    address: '1700 17-Mile Drive',
    city: 'Carmel-by-the-Sea',
    region: 'California',
    country: 'United States',
    description:
      'A breathtaking links-style course set along the rugged California coastline, Coastal Links at Carmel Bay offers 18 holes of windswept challenge with panoramic Pacific Ocean views. Designed by Tom Doak in 2001, the course features native fescue fairways, pot bunkers, and dramatic elevation changes. Ocean fog rolls in from the bay each afternoon, making club selection a strategic art.',
    holes: 18,
    par: 71,
    yardage: 7_110,
    rating: 74.3,
    slope: 138,
    established: '2001',
    designer: 'Tom Doak',
    tournamentId: 't2',
    holeData: [
      { hole: 1,  par: 4, yards: 390, handicap: 9  },
      { hole: 2,  par: 4, yards: 450, handicap: 3  },
      { hole: 3,  par: 3, yards: 185, handicap: 17 },
      { hole: 4,  par: 4, yards: 430, handicap: 7  },
      { hole: 5,  par: 5, yards: 540, handicap: 13 },
      { hole: 6,  par: 4, yards: 405, handicap: 5  },
      { hole: 7,  par: 3, yards: 220, handicap: 11 },
      { hole: 8,  par: 4, yards: 470, handicap: 1  },
      { hole: 9,  par: 4, yards: 385, handicap: 15 },
    ],
  },
  {
    id: 'c3',
    geo: { lat: 35.0526, lng: -83.1968 },
    phone: '+1 (828) 555-0130',
    website: 'highlandsridge.com',
    dressCode: 'Collared shirts; no denim. Soft spikes only.',
    name: 'Highlands Ridge Golf Resort',
    imageUrl: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&h=500&fit=crop&auto=format',
    location: 'Highlands, North Carolina, USA',
    address: '901 Golf Course Road',
    city: 'Highlands',
    region: 'North Carolina',
    country: 'United States',
    description:
      'Situated 4,000 feet above sea level in the Blue Ridge Mountains, Highlands Ridge Golf Resort delivers mountain golf at its finest. The cool mountain air adds distance to every club, while the dramatic elevation changes and stunning vistas make every round memorable. Architect Rees Jones masterfully routed the course through mature hardwood forest and across mountain streams.',
    holes: 18,
    par: 72,
    yardage: 7_050,
    rating: 73.9,
    slope: 136,
    established: '1994',
    designer: 'Rees Jones',
    tournamentId: 't3',
    holeData: [
      { hole: 1, par: 4, yards: 420, handicap: 11 },
      { hole: 2, par: 5, yards: 560, handicap: 5  },
      { hole: 3, par: 3, yards: 195, handicap: 15 },
      { hole: 4, par: 4, yards: 440, handicap: 1  },
      { hole: 5, par: 4, yards: 385, handicap: 13 },
      { hole: 6, par: 5, yards: 530, handicap: 7  },
      { hole: 7, par: 3, yards: 160, handicap: 17 },
      { hole: 8, par: 4, yards: 445, handicap: 3  },
      { hole: 9, par: 4, yards: 415, handicap: 9  },
    ],
  },
]

export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: 't1',
    name: 'Augusta Pines Classic Open',
    dateRange: 'Oct 12–15, 2026',
    startDate: '2026-10-12',
    endDate: '2026-10-15',
    time: '7:30 AM shotgun start',
    venue: 'Augusta Pines Golf Club',
    location: 'Augusta, Georgia, USA',
    city: 'Augusta, Georgia',
    country: 'United States',
    status: 'registration-open',
    format: 'Stroke Play',
    category: 'Amateur Open Division',
    description:
      'The Augusta Pines Classic Open is the premier amateur strokeplay event in the American South. Now in its 18th year, the tournament attracts over 100 of the region\'s finest amateur golfers competing across four rounds for the historic sterling trophy. The course will be set up at full championship distance with USGA-compliant conditions.',
    courseId: 'c1',
    registrationStatus: 'open',
    players: 87,
    maxPlayers: 120,
    entryFee: '$250',
    prize: 'Sterling Trophy + $5,000',
    imageUrl: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&h=500&fit=crop&auto=format',
  },
  {
    id: 't2',
    name: 'Carmel Bay Stableford Cup',
    dateRange: 'Nov 8–10, 2026',
    startDate: '2026-11-08',
    endDate: '2026-11-10',
    time: '8:00 AM tee times',
    venue: 'Coastal Links at Carmel Bay',
    location: 'Carmel-by-the-Sea, CA, USA',
    city: 'Carmel-by-the-Sea',
    country: 'United States',
    status: 'upcoming',
    format: 'Stableford',
    category: 'Open Division (all handicaps)',
    description:
      'Set against the dramatic backdrop of the California coastline, the Carmel Bay Stableford Cup is a three-day celebration of golf. The modified Stableford scoring format rewards bold, attacking play while protecting against blowout holes. Players of all handicap levels are welcomed. Ocean views from every hole make this one of the most scenic events on the calendar.',
    courseId: 'c2',
    registrationStatus: 'coming-soon',
    players: 0,
    maxPlayers: 80,
    entryFee: '$320',
    prize: 'Crystal Trophy + $3,500',
    imageUrl: 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=800&h=500&fit=crop&auto=format',
  },
  {
    id: 't3',
    name: 'Blue Ridge Four-Ball Championship',
    dateRange: 'Sep 27–28, 2026',
    startDate: '2026-09-27',
    endDate: '2026-09-28',
    time: '8:30 AM tee times',
    venue: 'Highlands Ridge Golf Resort',
    location: 'Highlands, North Carolina, USA',
    city: 'Highlands, North Carolina',
    country: 'United States',
    status: 'registration-open',
    format: 'Four-Ball',
    category: 'Net & Gross Divisions',
    description:
      'The Blue Ridge Four-Ball Championship pairs golfers in teams of two for a weekend of competitive partner golf at altitude. Playing at 4,000 feet above sea level, the cool mountain air and stunning hardwood forest create an unforgettable setting. Both gross and net divisions ensure competitive play for all handicap levels. Pre-registration must include both partner names.',
    courseId: 'c3',
    registrationStatus: 'registered',
    players: 56,
    maxPlayers: 64,
    entryFee: '$180/team',
    prize: 'Mountain Crystal Trophy',
    imageUrl: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&h=500&fit=crop&auto=format',
  },
  {
    id: 't4',
    name: 'Lowcountry Scramble Invitational',
    dateRange: 'Aug 2, 2026',
    startDate: '2026-08-02',
    endDate: '2026-08-02',
    time: '9:00 AM shotgun start',
    venue: 'Savannah Golf Club',
    location: 'Savannah, Georgia, USA',
    city: 'Savannah, Georgia',
    country: 'United States',
    status: 'completed',
    format: 'Scramble',
    category: 'Mixed Invitational',
    description:
      'The Lowcountry Scramble Invitational brings together teams of four for a fun, fast-paced day of golf in historic Savannah. The scramble format — where the team plays from the best shot each hole — makes this event accessible and highly social. Past winners have posted scores as low as 15-under par. An end-of-day dinner and awards ceremony rounds out the experience.',
    courseId: 'c1',
    registrationStatus: 'closed',
    organizerId: 'o-savannah',
    players: 40,
    maxPlayers: 40,
    entryFee: '$120/team',
    prize: 'Lowcountry Perpetual Trophy',
    imageUrl: 'https://images.unsplash.com/photo-1530028828-25e8270793c5?w=800&h=500&fit=crop&auto=format',
  },
  {
    id: 't5',
    name: 'Palmetto Senior Classic',
    dateRange: 'Dec 5–6, 2026',
    startDate: '2026-12-05',
    endDate: '2026-12-06',
    time: '8:00 AM tee times',
    venue: 'Palmetto Dunes Golf Club',
    location: 'Hilton Head Island, SC, USA',
    city: 'Hilton Head Island',
    country: 'United States',
    status: 'published',
    format: 'Stroke Play',
    category: 'Senior Division (50+)',
    description:
      'Exclusively for golfers aged 50 and over, the Palmetto Senior Classic is a prestigious two-day strokeplay event held on the famous Palmetto Dunes course in Hilton Head Island. Championship conditions, professional tournament setup, and full rules officiating make this a genuine competitive experience. The senior field consistently produces some of the best scoring of any event on the calendar.',
    courseId: 'c2',
    registrationStatus: 'coming-soon',
    players: 0,
    maxPlayers: 100,
    entryFee: '$210',
    prize: '$4,000 + Senior Trophy',
    imageUrl: 'https://images.unsplash.com/photo-1611374243147-44a702c2d44c?w=800&h=500&fit=crop&auto=format',
  },
  {
    id: 't6',
    name: 'Georgia Junior Open',
    dateRange: 'Jul 18, 2026',
    startDate: '2026-07-18',
    endDate: '2026-07-18',
    time: '7:00 AM tee times',
    venue: 'Augusta Pines Golf Club',
    location: 'Augusta, Georgia, USA',
    city: 'Augusta, Georgia',
    country: 'United States',
    status: 'cancelled',
    format: 'Stroke Play',
    category: 'Junior Division (U18)',
    description:
      'Cancelled due to course renovation works. All registered players have been notified and entry fees fully refunded. The event is expected to return to the calendar in 2027.',
    courseId: 'c1',
    registrationStatus: 'closed',
    players: 0,
    maxPlayers: 60,
    entryFee: '$80',
    prize: 'Junior Trophy',
    imageUrl: 'https://images.unsplash.com/photo-1632946269126-0f8edbe8b068?w=800&h=500&fit=crop&auto=format',
  },
  {
    // Draft from an organiser still awaiting approval — hidden from golfers
    id: 't7',
    name: 'Monterey Bay Charity Scramble',
    dateRange: 'Nov 21, 2026',
    startDate: '2026-11-21',
    endDate: '2026-11-21',
    time: '10:00 AM shotgun start',
    venue: 'Coastal Links at Carmel Bay',
    location: 'Carmel-by-the-Sea, California, USA',
    city: 'Carmel-by-the-Sea, California',
    country: 'United States',
    status: 'draft',
    format: 'Scramble',
    category: 'Charity Fundraiser',
    description:
      'A relaxed four-person scramble raising funds for coastal conservation. Includes lunch, on-course contests and an evening auction overlooking the bay.',
    courseId: 'c2',
    registrationStatus: 'closed',
    organizerId: 'o-coastal',
    players: 0,
    maxPlayers: 72,
    entryFee: '$150',
    prize: 'Charity Cup',
    imageUrl: 'https://images.unsplash.com/photo-1592919505780-303950717480?w=800&h=500&fit=crop&auto=format',
  },
  {
    // Live now: round 1 under way — the golfer is in the field (live scoring, leaderboard, hole map)
    id: 't8',
    name: 'Augusta Pines Club Championship',
    dateRange: 'Oct 4–5, 2026',
    startDate: '2026-10-04',
    endDate: '2026-10-05',
    time: '7:30 AM tee times',
    venue: 'Augusta Pines Golf Club',
    location: 'Augusta, Georgia, USA',
    city: 'Augusta, Georgia',
    country: 'United States',
    status: 'in-progress',
    format: 'Stroke Play',
    category: 'Club Championship',
    description:
      'The 36-hole club championship over two days. Gross champion takes the Hartwell Cup; net winners in each division receive pro-shop credit.',
    courseId: 'c1',
    registrationStatus: 'registered',
    players: 16,
    maxPlayers: 48,
    entryFee: '$95',
    prize: 'Hartwell Cup + $1,000 pro-shop credit',
    imageUrl: 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=800&h=500&fit=crop&auto=format',
    rounds: [
      { number: 1, date: '2026-10-04', holes: 'all' },
      { number: 2, date: '2026-10-05', holes: 'all' },
    ],
    scoring: { basis: 'gross-and-net', allowancePct: 95, maxHandicap: 28, tieBreak: 'countback', cutAfterRound: 0, cutSize: 0 },
    eligibility: { gender: 'open', membersOnly: true, officialHandicapRequired: true, maxHandicap: 28 },
    divisions: [
      { id: 'div-a', name: 'Championship (0–9.9)', minHandicap: -10, maxHandicap: 9.9, teeSetId: 'tee-black' },
      { id: 'div-b', name: 'Division B (10–18.9)', minHandicap: 10, maxHandicap: 18.9, teeSetId: 'tee-blue' },
      { id: 'div-c', name: 'Division C (19–28)', minHandicap: 19, maxHandicap: 28, teeSetId: 'tee-red' },
    ],
    registration: {
      opensAt: '2026-09-01T09:00', closesAt: '2026-10-01T18:00', waitlist: true, withdrawBy: '2026-09-28T18:00',
      refundPolicy: 'Full refund until Sep 28; no refund after the draw is published.',
    },
    fees: { currency: 'USD', amount: 95, memberAmount: 95, perTeam: false, includes: ['Green fee', 'Cart', 'Range balls', 'Dinner / prize giving'] },
    prizes: [
      { id: 'prz-1', label: 'Gross champion', value: 'Hartwell Cup + $1,000 pro-shop credit' },
      { id: 'prz-2', label: 'Net winner', divisionId: 'div-b', value: '$300 pro-shop credit' },
      { id: 'prz-3', label: 'Net winner', divisionId: 'div-c', value: '$300 pro-shop credit' },
      { id: 'prz-4', label: 'Closest to the pin (16th)', value: 'Club driver' },
    ],
    teeSheet: { startType: 'tee-times', firstTeeTime: '07:30', intervalMinutes: 10, groupSize: 4, startingTees: 'first' },
    officials: [
      { name: 'Dana Whitfield', role: 'Tournament director', phone: '+1 (706) 555-0110' },
      { name: 'Marcus Lee', role: 'Rules official', phone: '+1 (706) 555-0124' },
    ],
    contactEmail: 'events@augustapines.com',
    contactPhone: '+1 (706) 555-0100',
    localRules: [
      'Preferred lies on closely mown areas through the green.',
      'Red stakes on the 16th: drop zone available short of the water.',
      'Pace of play: 4 h 15 min per round; groups out of position will be timed.',
    ].join('\n'),
  },
]

/**
 * Fields the create/edit wizards require that the original demo records don't have
 * (postal codes, tournament contacts). Also applied to data saved by older versions.
 */
const SEED_POSTAL: Record<string, string> = { c1: '30907', c2: '93923', c3: '28741' }
export function fillSeedGaps(courses: Course[], tournaments: Tournament[]) {
  for (const c of courses) if (!c.postalCode && SEED_POSTAL[c.id]) c.postalCode = SEED_POSTAL[c.id]
  for (const t of tournaments) {
    const site = courses.find(c => c.id === t.courseId)?.website
    if (!t.contactPerson) t.contactPerson = t.officials?.[0]?.name ?? 'Tournament office'
    if (!t.contactEmail && site) t.contactEmail = `events@${site.replace(/^https?:\/\//, '').replace(/\/.*$/, '')}`
  }
}

// Fill structured set-up (tee sets, hole maps, rounds, scoring, fees…) for every seed record
MOCK_COURSES.splice(0, MOCK_COURSES.length, ...MOCK_COURSES.map(withCourseDefaults))
MOCK_TOURNAMENTS.splice(0, MOCK_TOURNAMENTS.length, ...MOCK_TOURNAMENTS.map(withTournamentDefaults))
fillSeedGaps(MOCK_COURSES, MOCK_TOURNAMENTS)

export function getCourse(id: string): Course | undefined {
  return MOCK_COURSES.find(c => c.id === id)
}

export function getTournament(id: string): Tournament | undefined {
  return MOCK_TOURNAMENTS.find(t => t.id === id)
}

/** All tournaments at a course, including drafts — golfer screens filter with isPublicTournament */
export function getTournamentsByCourse(courseId: string): Tournament[] {
  return MOCK_TOURNAMENTS.filter(t => t.courseId === courseId)
}
